### ISSUE TITLE
⚙ Husky & Prettier & EsLint Set Up

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/blog#1]
## Description
Husky & Prettier & EsLint Set Up

## To-do
- [x] Prettier, Husky, and ESLint setting:
- [x] Configure Prettier for code formatting
- [x] Set up Husky for pre-commit and pre-push hooks
- [x] Configure ESLint for code listing

## Additional context
**Add any other context or screenshots about the feature request here.**

## Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
